import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google";
import { ReactNode } from "react";

const montserrat = Montserrat({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: ReactNode,
  members: ReactNode,
  comments: ReactNode,
}

export default function RootLayout({
  children,
  comments,
  members,
}: Readonly<Props>) {
  return (
    <html lang="en">
      <body
        className={montserrat.className}
      >
        <h1>
          {children}
        </h1>
        <div className="flex">
          {comments}
          {members}
        </div>
      </body>
    </html>
  );
}
